# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apivincent

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.11]
    steps:
        # Setup which version of Python to use
      - name: Checkout repository files
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

        # Install pytest
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Run the tests
      - name: Run tests
        run: pytest
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://apivincent.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9f69073051924d8686e2b4ae0e0a892e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_23f37602fe0d47a783757081a2e8e836 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: apivincent.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9f69073051924d8686e2b4ae0e0a892e }}/apivincent:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'apivincent'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a7f7a747ede5431cb6b29a299617cfd1 }}
        images: 'apivincent.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9f69073051924d8686e2b4ae0e0a892e }}/apivincent:${{ github.sha }}'